# Database
spring.datasource.url=jdbc:h2:mem:novotestdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging - Para debug de JWT:
logging.level.org.springframework.security=DEBUG
logging.level.com.dio.config=DEBUG
logging.level.com.dio.service=DEBUG

# JWT
jwt.expiration=86400000  # 24 horas